services:
  - type: web
    name: pos-roadworthy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PANTANAN_WHATSAPP_LINK
        value: https://wa.me/639695093050
      - key: PANTANAN_MESSENGER_LINK
        value: https://facebook.com/alexander.moreno.2929
